export default {
  /* Project CRUD actions */
  CREATE_PROJECT: 'CREATE_PROJECT',
  CREATE_PROJECT_SUCCESS: 'CREATE_PROJECT_SUCCESS',
  CREATE_PROJECT_FAILURE: 'CREATE_PROJECT_FAILURE',

  RETRIEVE_PROJECT: 'RETRIEVE_PROJECT',
  RETRIEVE_PROJECT_SUCCESS: 'RETRIEVE_PROJECT_SUCCESS',
  RETRIEVE_PROJECT_FAILURE: 'RETRIEVE_PROJECT_FAILURE',

  UPDATE_PROJECT: 'UPDATE_PROJECT',
  UPDATE_PROJECT_SUCCESS: 'UPDATE_PROJECT_SUCCESS',
  UPDATE_PROJECT_FAILURE: 'UPDATE_PROJECT_FAILURE',

  DELETE_PROJECT: 'DELETE_PROJECT',
  DELETE_PROJECT_SUCCESS: 'DELETE_PROJECT_SUCCESS',
  DELETE_PROJECT_FAILURE: 'DELETE_PROJECT_FAILURE',

  /* User CRUD actions */
  CREATE_USER: 'CREATE_USER',
  CREATE_USER_SUCCESS: 'CREATE_USER_SUCCESS',
  CREATE_USER_FAILURE: 'CREATE_USER_FAILURE',

  RETRIEVE_USER: 'RETRIEVE_USER',
  RETRIEVE_USER_SUCCESS: 'RETRIEVE_USER_SUCCESS',
  RETRIEVE_USER_FAILURE: 'RETRIEVE_USER_FAILURE',

  UPDATE_USER: 'UPDATE_USER',
  UPDATE_USER_SUCCESS: 'UPDATE_USER_SUCCESS',
  UPDATE_USER_FAILURE: 'UPDATE_USER_FAILURE',

  DELETE_USER: 'DELETE_USER',
  DELETE_USER_SUCCESS: 'DELETE_USER_SUCCESS',
  DELETE_USER_FAILURE: 'DELETE_USER_FAILURE',

  /* Floor CRUD actions */
  CREATE_FLOOR: 'CREATE_FLOOR',
  CREATE_FLOOR_SUCCESS: 'CREATE_FLOOR_SUCCESS',
  CREATE_FLOOR_FAILURE: 'CREATE_FLOOR_FAILURE',

  RETRIEVE_FLOOR: 'RETRIEVE_FLOOR',
  RETRIEVE_FLOOR_SUCCESS: 'RETRIEVE_FLOOR_SUCCESS',
  RETRIEVE_FLOOR_FAILURE: 'RETRIEVE_FLOOR_FAILURE',

  UPDATE_FLOOR: 'UPDATE_FLOOR',
  UPDATE_FLOOR_SUCCESS: 'UPDATE_FLOOR_SUCCESS',
  UPDATE_FLOOR_FAILURE: 'UPDATE_FLOOR_FAILURE',

  DELETE_FLOOR: 'DELETE_FLOOR',
  DELETE_FLOOR_SUCCESS: 'DELETE_FLOOR_SUCCESS',
  DELETE_FLOOR_FAILURE: 'DELETE_FLOOR_FAILURE',

  /* File CRUD actions */
  CREATE_FILE: 'CREATE_FILE',
  CREATE_FILE_SUCCESS: 'CREATE_FILE_SUCCESS',
  CREATE_FILE_FAILURE: 'CREATE_FILE_FAILURE',

  RETRIEVE_FILE: 'RETRIEVE_FILE',
  RETRIEVE_FILE_SUCCESS: 'RETRIEVE_FILE_SUCCESS',
  RETRIEVE_FILE_FAILURE: 'RETRIEVE_FILE_FAILURE',

  UPDATE_FILE: 'UPDATE_FILE',
  UPDATE_FILE_SUCCESS: 'UPDATE_FILE_SUCCESS',
  UPDATE_FILE_FAILURE: 'UPDATE_FILE_FAILURE',

  DELETE_FILE: 'DELETE_FILE',
  DELETE_FILE_SUCCESS: 'DELETE_FILE_SUCCESS',
  DELETE_FILE_FAILURE: 'DELETE_FILE_FAILURE',


};